from functools import reduce
import re
import time
li=["","split","0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/","slice","indexOf","","",".","pow","reduce","reverse","0"]
def deez(a=None,b=None,c=None):
    d=list(li[2])
    #print(d)
    e=d[:b]
    f=d[:c]
    g=list(str(a))
    g.reverse()
    sumer=0
    def nutz(bc,cd):
        nonlocal sumer
        bc+=int(cd)*b**sumer
        sumer+=1
        return bc
    g=reduce(nutz,g,0)
    h=''
    while g>0:
        h=f[int(g%c)]+h
        g=(g-(g%c))/c
    return h if h!="" else li[11]
    

def token_extractor(ab=None,bc=None,c=None,de=None,ef=None,fg=None):
    Ir=''
    mi=len(ab)
    x=0
    while x<mi:
        s=''
        while ab[x]!=c[ef]:
            s+=ab[x]
            x+=1
        im=len(c)
        #print(s,ef)
        #print(x)
        for y in range(im):
            s=re.sub(c[y],str(y),s)
        #print(int(deez(int(s),ef,10))-de)
        Ir+=chr(int(deez(s,ef,10))-de)
        x+=1
    return Ir

if __name__=="__main__":
    t1=time.perf_counter()
    token=token_extractor("kkuKXWuiXKuiiXuiKKuKkyuiKkuiXCuiKiuiKKuKXWuKXCukWuiiyuCwuiiKuKkCuiKwukWuiiXuiKwuiXkukWuKWXukWuKXiuKKiuiXXuKKiuiXKuiiCuKKkuKWkuKwWuiiCuKWwuKiiuKKkuKkwuKwyuKwWuKWiuKkCuiiXuiKkuiKiuiKWuiXkuKkCuiiCuKWXuKKCuKXiuKiyuCwuiXKuiiXuiKKuKkyuiKkuiXCuiKiuiKKukWuKkyuiXWuKkCuiKKuiXiuiXXuKwyuiKwuKkyuKXWuiKyuiKwuKkyuKXCukWuiiyuCwukkuKXWuKXiuiXCuiXKuiKwuKkCuiKXuiXXuKKKuiXXuiKXuKkwuiXXuKkkuKKXuiKwuiXXuiKyuiKWuiKiuiKKuiKyuiXCuiiKuiXXuKKXuiXCuiKkuiXXuiKXuKXiuKXCuKKKuKkCuiKkuiKkuiKwuKXWuKXiuiKyuiKwuKkyuKXiuKXkukWuiKyuiKwuKkyuKXCuKiyuCwuiWXuCwukkuKXWuKXiuKKKuiXkuiKiuKkCuKkkuKKXuiKWuiXkuKkCuiiCuiXXuiKwuKXiuKXCuKKKuKkyuiXkuiXCuKkyuiXyuKXWuiXKuiiXuiKKuKkyuiKkuiXCuiKiuiKKuKXWuiXXuKXCukWuiiyuCwuKkyuiXWuKkCuiKKuiXiuiXXuKwyuiKwuKkyuKXWuiiXuiKwuiXkuKXCuKiyuCwukkuKXWuiKkuiXWuiXCuiKyuKXCuKKKuiKwuiXXuiKXuiKiuiiKuiXXuKXWuKXCuKiyuCwuiXXuKKKuiKWuiKwuiXXuiiKuiXXuiKKuiKkuKWkuiXXuiXKuKkCuiiXuiXkuiKkuKXWuKXCuKiyuCwuiWXuKXCuKiyuCwuiiKuKkCuiKwukWuiKKuiKyuKiKuiXkuiiCuKyWuKiKuKwkuKKyuKCWuiXXuKkyuKiKuKWyuKkyuiXKuiKwuKkwuKkwuKywuKKyuiXyuiiWuKWyuKwkuKyXuiXKuKyCuiKwuiXwuKCwuKKyuKKkuiKXuKwCuiKwuKyXuKyKuiiwuKWkukWuKWXukWuKXiuiiiuKwkuKiXuiKCuiiKuiKiuiXwuKiXuiKXuiXWuKwiuKywuiXKuiXWuKKwuKkwuKyCuiXkuiXWuKWwuiiwuiiWuKyCuKCCuKCWuKCWuKKCuKiKuiKwuiKKuiKiuiXCuKCCuKWyuKwiuKiKuKCKuKyWuKiCuKCXuKXiuKiyuCwuiiKuKkCuiKwukWuiKwuiXKuiKkuiKiuiXkuiXKuKWCuiXKuKKkuiKKuKwXuKiWuKKwuKyXuKywuKwyuKWwuiKiuKWkuiiKuiiiuiiCuiXwuiXiuKyCuKiXuiKkuKCkuKyXuiiWuKCyuKkwuKCCuKkkuKCkuiXKuiKyuKCiuKKyuiKCukWuKWXukWuKXiuKwkuKKkuKCkuiiiuKkwuiiXuKKyuKyKuiKiuiXiuKCXuiKXuKwWuiKkuiXwuiXkuKwWuKKCuKwCuKKkuiXkuKwiuKCXuiKCuiiCuiXkuKyWuKWyuKyKuKyWuKCiuiKwuiXCuiXWuKCiuKkkuKyWuiXXuiKXuiKXuKXiuKiyuCwuiiKuKkCuiKwukWuKCyuKwXuKkwuKwwuKwiuKywuKyWuKiWuKKwuKCiuiXkuKkwuKyKuiiKuKWkuiKiuKyCuKKwuKwwuKiKuKiiuiXyuKCCuiXWuKiKuKkwuiiiuKyCuKiCuKCWuiKCuiXXuiiwuiXXuKCWuKKWuKiCuiiXuKyWuiKXukWuKWXukWuKXiuKwiuiiXuKywuKCkuKKCuKyKuKyiuiXwuKkyuKyWuKWCuKCWuiiCuKwCuKKWuKiWuKwyuKiXuKwKuiKiuKwwuKwKuiiKuKiiuiKXuKwWuKWkuKCCuKKyuiiWuKCCuKwCuiKWuiKiuKyKuiiwuKkkuKyXuiiXuKCCuKXiuKiyuCwuiiKuKkCuiKwukWuiiWuKCkuKiXuKKWuKWyuiiXuKiCuKkkuiXWuKyKuKCKuiKKuKKyuKyXuKkkuKKWuiXCuKCiuiKwuKwkuKkwuKywuKiCuiKyuKiiuiiXuKKkuKiKuKwyuKkCuiiKuiiXuiXWuKCWuKKCuKwCuiiiuKKyuKyCuKyCukWuKWXukWuKXiuKkkuKCkuKCKuiXXuKWCuiXXuKKwuiKCuiKXuKyCuiKCuKkyuKCkuKyCuiiwuKwwuiKWuiiWuKKyuKyXuiKiuiiCuKyCuKiXuiXKuiKXuiiiuiXkuiKwuiXkuKCCuKWCuKkwuiiXuKwXuKwXuKyWuKyXuiXXuKkCuKXiuKiyuCwuiiKuKkCuiKwukWuKkyuKyKuKWyuKkkuKKyuKkCuKkkuiKKuKWCuiKXuiiwuiiiuKCkuKiCuiKiuKCkuiXiuKCwuiiwuiKWuKyKuiXXuKyWuKCkuKCkuKwCuiKiuiXyuKwCuKCWuKWkuKKWuiXWuKkCuiKXuKwwuKwXuiXCuKWCuKKCukWuKWXukWuKXiuiKWuKwiuiKCuiiwuKCCuKiXuKCWuiXwuKkCuKwKuiiwuKwyuKyXuKiXuKwkuiiWuiKkuiXiuKKwuiiiuiXKuiXkuKWkuiXWuiKXuKWCuiKwuiKkuiiKuKwCuiiiuiiXuiiiuiiwuiiiuKwyuiKKuKkCuiXCuKwXuKXiuKiyuCwuiiKuKkCuiKwukWuKCyuiKXuKWkuKwiuKyXuKyWuiiCuiiWuKWCuKyWuiXyuKyCuKKCuiiWuiiCuiiWuKwyuiiWuKKwuKWkuiKkuKwXuKyCuKCkuKKwuKywuKyKuKWyuiKkuiKWuKiKuiiKuiKkuKiWuiiwuKwyuKyKuiiiuKWkuKKkukWuKWXukWuKXiuiXwuKkCuKiiuiKiuKiXuKCCuKwwuiXwuiKiuKiXuKwCuKiWuKWkuKwCuKyiuiiCuKWwuKCkuKkyuKyWuKyXuKCwuKkwuKwkuKwiuiKCuKyXuKyiuiiXuiiWuKCCuKCCuiXiuKwiuKkyuiiiuKCXuKkkuKCXuiKwuKXiuKiyuCwuiiKuKkCuiKwukWuiiiuKwKuKWkuiXwuKCkuiKKuiiCuiKwuKkwuKwXuKiiuKkyuKwiuKwwuKkkuKwkuKkkuiXKuKyCuKiWuKwkuKWkuKwKuiXiuKiCuiXkuKKWuiXyuiXXuKCXuKkyuKwkuKKwuKkCuKiXuKCXuKWCuKkkuiiiuKiKukWuKWXukWuKXiuKKyuiXkuKkwuKiCuiXwuKKyuiKCuKiCuKWCuKCwuKKkuiKkuKwCuiKiuKwWuKiKuiKCuiKwuKkkuKKwuKCyuKyWuKyWuKKyuiKWuKyWuKywuiXyuKiXuKKwuKWyuKKCuiiWuiXwuKywuKWkuKkwuiKKuKwwuKKwuKXiuKiyuCwuiiKuKkCuiKwukWuiiwuKwWuKKwuiXwuKwXuiKWuKkyuKkkuKwKuiKXuKKCuiiWuiXyuiiiuKyKuiiKuiXXuKkkuiiCuiKWuKCXuKyKuKKyuKwKuKwCuKyKuKWyuiKkuKKCuiXXuKyKuKwkuiiXuKKwuiiWuKKwuKKwuiiwuKCCuiiwukWuKWXukWuKXiuKwWuKKwuiXwuKwXuiKWuKkyuKkkuKwKuiKXuKKCuiiWuiXyuiiiuKyKuiiKuiXXuKkkuiiCuiKWuKCXuKyKuKKyuKwKuKwCuKyKuKWyuiKkuKKCuiXXuKyKuKwkuiiXuKKwuiiWuKKwuKKwuiiwuKCCuiiwuKkwuKXiuKiyuCwuiiKuKkCuiKwukWuKWCuiiXuKyWuKCwuKiiuKWCuKiXuKCiuKyXuKwWuKKCuKyXuKCCuKiiuKCXuKCkuKyXuiKCuiXwuKwWuiiWuiiCuKWyuKwiuKywuiXkuKkCuKwXuKCKuKCkuiiwuiKWuiKKuiXkuiKCuKyXuiiiuKWyuKCyuiiCukWuKWXukWuKXiuKCiuiKWuKWwuKCCuKCKuKCiuKWkuKCyuiXKuKwCuiKwuKWwuKiCuiiKuKwKuKCCuKKCuKKWuKiWuKkwuiKXuKiKuiXCuKiCuKywuiXwuKWkuKkCuiKwuiKXuKCwuKywuKCKuKiWuKyXuKyiuKyXuKwWuKwWuiiwuKXiuKiyuCwuiiKuKkCuiKwukWuiKiuKwCuiKyuKiWuKCiuiiKuiXXuKywuKWyuKwKuiKXuKwWuKiWuiKKuiXCuKWCuKKyuKwCuKWyuKCKuKiiuKCCuKKCuKkCuiiWuKyWuiXCuiXWuiKKuiiwuiKCuKwwuKWCuiKwuKKyuKWCuKiCuKkCuKkwuiXWukWuKWXukWuKXiuiKXuKiCuKwXuiKyuKyiuKywuKkkuKiXuKCiuiKKuKyCuKwCuKkCuKwiuKwiuKkkuiXCuiXCuKCyuKkCuiKiuiKkuKkwuKiWuKwCuKKWuKkyuiKWuiiCuKiXuKyWuKKCuKwwuKwKuKwyuKwXuiKkuiiKuiXWuKCWuKXiuKiyuCwuiiKuKkCuiKwukWuiiiuiiwuiXyuKKCuiKXuKKkuiXCuKwyuKiKuiKiuiXwuiKwuKyCuKyXuKkkuKwCuKkwuKCkuKwWuKkCuKKyuKkwuiiKuiiWuKCCuKyWuiXkuKCiuKCwuiKXuKiXuiKiuKCCuKKCuKyKuKCiuKyXuiKCuiXiuKkkukWuKWXukWuKXiuKwyuiXXuiKKuKCkuiiXuiKCuiXwuKkyuKCCuKCwuKWwuKwiuKiWuiXkuKiKuKCyuKCXuKCXuiKWuiiXuiKwuKiiuKCWuKCWuKwkuiXiuKKwuiiKuKyKuiKXuiKKuKCkuKCWuKwXuiKXuiiCuiiXuiiCuiiWuKyWuKXiuKiyuCwuiiKuKkCuiKwukWuiKXuKwyuiXXuiKKuKCkuiiXuiKCuiXwuKkyuKCCuKCwuKWwuKwiuKiWuiXkuKiKuKCyuKCXuKCXuiKWuiiXuiKwuKiiuKCWuKCWuKwkuiXiuKKwuiiKuKyKuiKXuiKKuKCkuKCWuKwXuiKXuiiCuiiXuiiCuiiWukWuKWXukWuKXiuKiWuKCiuKkCuKiWuKyiuKWkuKCWuKWyuKwCuiXwuKWyuiKwuiXwuKCCuiXKuKwKuKWwuiKkuiiCuKWwuiiXuKwXuKwkuKkCuKiXuKwwuiKWuKWwuKCWuiKwuiiwuKKWuKwWuKyiuiiiuiXXuKKWuKCiuiXkuKiCuKXiuKiyuCwuiiKuKkCuiKwukWuKWyuKwCuKKkuKkkuKiXuiXyuKWCuKkwuKwwuiKCuKCKuKkkuKwCuiKXuKCWuKKkuKCwuKywuKiiuiKCuiXwuKKCuiiXuKKCuKKCuKkCuKwiuiXCuiiiuiKWuKCXuiKiuKyWuiXiuiiXuKCwuKwXuiXKuiiCuiiXukWuKWXukWuKXiuKwCuKKkuKkkuKiXuiXyuKWCuKkwuKwwuiKCuKCKuKkkuKwCuiKXuKCWuKKkuKCwuKywuKiiuiKCuiXwuKKCuiiXuKKCuKKCuKkCuKwiuiXCuiiiuiKWuKCXuiKiuKyWuiXiuiiXuKCwuKwXuiXKuiiCuiiXuKiKuKXiuKiyuCwuiiKuKkCuiKwukWuKWCuKwWuKkwuKKwuKwKuiXKuKiXuKyWuKwwuKKyuKwKuKyXuiiiuKWkuiXCuiKiuKCkuiiKuiiKuKywuiiiuKCiuKiCuKkkuKwwuKKkuiXWuKiKuKiWuiXwuKiKuiXXuiXwuiKCuKKWuiiKuiXkuKkkuiKXuiiXukWuKWXukWuKXiuKwWuKkwuKKwuKwKuiXKuKiXuKyWuKwwuKKyuKwKuKyXuiiiuKWkuiXCuiKiuKCkuiiKuiiKuKywuiiiuKCiuKiCuKkkuKwwuKKkuiXWuKiKuKiWuiXwuKiKuiXXuiXwuiKCuKKWuiiKuiXkuKkkuiKXuiiXuKKWuKXiuKiyuCwuiiKuKkCuiKwukWuiiwuKyWuKywuKCKuKiCuKWwuKiXuiiwuKiiuKwCuiXkuKyWuiiWuKkkuKyWuKCWuKCXuKkwuKyiuiXkuKKCuKCwuKiCuKkkuKCkuKiKuiiCuKwiuiiCuiiWuKCXuiKCuKKkuKkyuKKWuiiCuiiCuKywuiiWuiKWukWuKWXukWuKXiuKyWuKiXuKKwuiKwuKWCuKiWuiXCuKKkuKiCuiXiuKyKuKCWuKCyuiKCuKkkuiKXuKwyuKWwuKyWuiXCuKyiuKWyuiXwuiKkuKkCuKCWuKiiuiiiuiiwuKCkuKCWuKyCuKyXuKKwuKyWuKywuiiWuKKwuKyiuKiXuKXiuKiyuCwuiiKuKkCuiKwukWuiiXuKyWuKiXuKKwuiKwuKWCuKiWuiXCuKKkuKiCuiXiuKyKuKCWuKCyuiKCuKkkuiKXuKwyuKWwuKyWuiXCuKyiuKWyuiXwuiKkuKkCuKCWuKiiuiiiuiiwuKCkuKCWuKyCuKyXuKKwuKyWuKywuiiWuKKwuKyiukWuKWXukWuKXiuKwXuKwKuiKyuKKyuKwwuKKWuKiWuiKWuiKkuKyKuiKiuiXwuKiXuKiWuKCKuiKKuiKwuKyCuKWyuKyCuKCWuiKwuKkCuKywuKKCuiXKuKiXuiXkuKwyuKyKuKWyuiKCuKyWuKyCuKCXuKKwuKCCuKWkuiXCuKwiuKXiuKiyuCwukkuKXWuKXiuKKKuKkCuKkkuKwyuiXXuiKKuiKyuiXXuKiwuiXXuiKCuKXWuKKCuKXCuKXiuKXCuKKKuiXWuiKkuiKXuiXkuKXWuKXiuKikuiXKuiKiuiKwuiKXukWuKkCuKkyuiKkuiXCuiKiuiKKuKWXukwuiXWuiKkuiKkuiKWuiKyuKiwuKKiuKKiuiXyuiiiuiXCuiXyuKKKuiKyuiXCuKKiuKkkuKKiuiXCuKCKuKiXuKCXuKWwuKCCuKiCuiiXuKkwuKywuKywuKCKukwukWuiKXuiXXuiKkuiXWuiKiuKkkuKWXukwuKwWuKwiuKwyuKwkukwuKWKuKikuiXCuiKKuiKWuiiXuiKkukWuiKkuiiCuiKWuiXXuKWXukwuiXWuiXCuKkkuKkkuiXXuiKKukwukWuiKKuKkCuiKXuiXXuKWXukwuKkiuiKkuiKiuiXyuiXXuiKKukwukWuiiKuKkCuiXkuiiXuiXXuKWXukwuKiiuKkyuiXyuiiXuKKkuKyiuKiWuKKCuKWwuiKyuKKWuKwKuKwXuiXXuiiKuiKyuKiCuKyCuKywuKWCuKyiuiiwuKkyuKkkuKWCuiiXuiKCuKCyuiXkuKyiuiXkuKyiuKWyuiXyuKyiuiiiuKkCuiiwuiKyuiiwukwuKWKuKikuKkwuiiXuiKkuiKkuiKiuiKKukWuiKkuiiCuiKWuiXXuKWXukwuiKyuiiXuKkwuiKXuiXCuiKkukwukWuKkyuiXkuKkCuiKyuiKyuKWXukwuKkwuiiXuiKkuiKkuiKiuiKKukWuiXCuiKyuKKXuiiXuiKWuiKWuiXXuiKwuKkyuKkCuiKyuiXXukWuiXCuiKyuKKXuiKyuiiXuKkyuKkyuiXXuiKyuiKyukWuiXCuiKyuKKXuiXKuiiXuiXkuiXkuiiiuiXCuKkkuiKkuiXWukwukWuiKkuiXCuiKkuiXkuiXXuKWXukwuKwyuiKiuiKwuiKwuiiCukWuiXKuiKiuiKwukWuiKkuiXWuiXXukWuKkCuKkkuiKyuKXkukWuiiiuiXXukWuiKwuiXXuKkCuiXkuiXkuiiCukWuiKKuiXXuiXXuKkkukWuiKkuiXWuiXXuiKXukWuiKkuiKiukWuiKWuKkCuiiCukWuiKyuiXXuiKwuiiKuiXXuiKwukWuKkwuiXCuiXkuiXkuiKyukWuKkCuiKKuKkkukWuiKkuiKiukWuiXyuiXXuiXXuiKWukWuiKkuiXWuiXXukWuiKyuiXCuiKkuiXXukWuiiXuiKWukCukwuKWKuKikuiKyuiKWuKkCuiKKuKWKuKWkuiKiuiiiuiKKuiXkuiKiuKkCuKkkuKXKuiKKuKkwuiKyuiKWuKiyuKXWuKKyuKKCuKiCuKKKuKiCuKiXukWuKwXuKWwuKXCuKikuKKiuiKyuiKWuKkCuiKKuKWKuKikuKKiuKkwuiiXuiKkuiKkuiKiuiKKuKWKuKikuKKiuiXKuiKiuiKwuiKXuKWKuKXiuKXCuKiyuCwuiWXuKXCuKiyu",98,"XKiWCwyku",27,8,29)
    t2=time.perf_counter()
    timep=t2-t1
    print(token)
    print(timep)
    
